pulsar:
  ## disable pulsar-manager
  components:
    pulsar_manager: true

  imagePullSecrets:
    - name: myregistrykey

  ## disable monitoring stack
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

  image:
    repository: apachepulsar/pulsar-all
    tag: 3.0.5
    pullPolicy: Always

  zookeeper:
    replicaCount: 1
    # Disable pod monitor since we're disabling CRD installation
    podMonitor:
      enabled: false

  bookkeeper:
    replicaCount: 1
    # Disable pod monitor since we're disabling CRD installation
    podMonitor:
      enabled: false

  autorecovery:
    # Disable pod monitor since we're disabling CRD installation
    podMonitor:
      enabled: false

  broker:
    replicaCount: 1
    # Disable pod monitor since we're disabling CRD installation
    podMonitor:
      enabled: false

  proxy:
    replicaCount: 1
    # Disable pod monitor since we're disabling CRD installation
    podMonitor:
      enabled: false
